# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 19:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_bid_customer_material_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='accessory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Accessory'),
        ),
        migrations.AddField(
            model_name='bid',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Customer'),
        ),
        migrations.AddField(
            model_name='bid',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime(2016, 10, 3, 19, 44, 50, 499903, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='bid',
            name='month',
            field=models.DateField(default=datetime.datetime(2016, 10, 3, 19, 44, 50, 499903, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='bid',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='bid',
            name='year',
            field=models.DateField(default=datetime.datetime(2016, 10, 3, 19, 44, 50, 499903, tzinfo=utc)),
        ),
    ]
