# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20161003_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Контрагент', 'verbose_name_plural': 'Контрагенты'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размер', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.RemoveField(
            model_name='bid',
            name='month',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='year',
        ),
        migrations.AddField(
            model_name='bid',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='material',
            name='name',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='size',
            name='name',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AlterField(
            model_name='bid',
            name='delivery_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
