# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20161004_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='material',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.Material'),
        ),
        migrations.AddField(
            model_name='bid',
            name='size',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.Size'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='accessory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.Accessory'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.Customer'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
