# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20161004_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='amount_meter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bid',
            name='amount_psc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bid',
            name='weight_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bid',
            name='weight_unit',
            field=models.IntegerField(default=0),
        ),
    ]
