# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20161004_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount_meter',
            field=models.FloatField(default=0),
        ),
    ]
