# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20161005_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Accessory'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Customer'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Material'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Size'),
        ),
    ]
