# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20161005_0021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accessory',
            new_name='Model',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='accessory',
            new_name='model',
        ),
    ]
