# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20161007_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=255, verbose_name='Наименование материалов')),
                ('unit', models.CharField(default=0, max_length=255, verbose_name='Ед. измерения')),
                ('expense', models.FloatField(default=0, verbose_name='Норма расхода')),
                ('loss', models.FloatField(default=0, verbose_name='Потери')),
                ('total_expense', models.FloatField(default=0, verbose_name='Итого норма расхода')),
            ],
            options={
                'verbose_name': 'Состав',
                'verbose_name_plural': 'Состав',
            },
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AddField(
            model_name='model',
            name='composition',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.Composition', verbose_name='Состав'),
        ),
    ]
