# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20161007_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='composition',
        ),
        migrations.AddField(
            model_name='composition',
            name='model',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.Model', verbose_name='Модель'),
        ),
    ]
