# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20161008_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.FloatField(default=1),
        ),
    ]
