# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20161008_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
