# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='model',
        ),
    ]
