# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_temp_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Model'),
            preserve_default=False,
        ),
    ]
