# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_temp_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Bid')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Composition')),
            ],
        ),
    ]
