# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-11 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20161206_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rawmaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование сырья')),
                ('ral', models.CharField(max_length=255, verbose_name='RAL')),
                ('rm_profile', models.FloatField(verbose_name='Сырьё на профиль, кг/м')),
                ('rm_repurposing', models.FloatField(verbose_name='Сырьё на переналадку, кг')),
                ('series', models.FloatField(verbose_name='Серия, кг/1000 м.п.')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Composition')),
            ],
            options={
                'verbose_name_plural': 'Сырьё',
                'verbose_name': 'Сырьё',
            },
        ),
    ]
