# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-11 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_composition_ismanufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Composition', verbose_name='Комплектующая'),
        ),
    ]
